ARG BUZZ_IMAGE=ghcr.io/arieldiaz/humanwareos-buzz@sha256:3a3322a9cb7884cc1da66c08e591162fed83312f0dfc794e575ac94333f5f5b6
FROM ${BUZZ_IMAGE}

LABEL org.humanwareos.buzz.config-revision="2026-08-17-default-invite-channels"

EXPOSE 3000 8080
